// Statische Spieldaten: Items, Gegner, NPCs, Quests, Klassen, Fraktionen, Gebäude.
export const ORIGINS = {
  farmhand:  { name:'Feldknecht', desc:'Du hast mehr Erde gesehen als Gold. Deine Hände sind hart, dein Rücken hält.',
               attrs:{strength:1,endurance:2}, skills:{survival:5,crafting:4}, gear:['axe','cloth_shirt','bread'], gold:8 },
  hunter:    { name:'Jäger', desc:'Der Wald hat dich ernährt. Du weißt, wann etwas dich beobachtet.',
               attrs:{agility:2,perception:1}, skills:{archery:8,survival:6,hunting:6}, gear:['shortbow','leather_jerkin','dried_meat'], gold:12 },
  apprentice:{ name:'Lehrling', desc:'Du hast Zeichen gelernt, die andere nicht lesen. Der Meister ist tot.',
               attrs:{intelligence:2,willpower:1}, skills:{crafting:7,medicine:5}, gear:['dagger','cloth_shirt','herb','herb'], gold:22 },
  soldier:   { name:'Ehemaliger Soldat', desc:'Du hast für Valen gestanden. Du hast aufgehört, es zu erklären.',
               attrs:{strength:2,endurance:1}, skills:{onehanded:9,defense:7}, gear:['rusty_sword','wooden_shield','leather_jerkin'], gold:10, rep:{valen:10} },
  wanderer:  { name:'Wanderer', desc:'Kein Heim, kein Herr, keine Schulden. Noch nicht.',
               attrs:{agility:1,perception:1,willpower:1}, skills:{survival:4,trading:4}, gear:['rusty_sword','cloth_shirt','bread'], gold:30 },
};

export const SKILL_NAMES = { onehanded:'Einhändig', twohanded:'Zweihändig', polearms:'Stangenwaffen', archery:'Bogen', defense:'Verteidigung',
  medicine:'Medizin', survival:'Überleben', hunting:'Jagd', crafting:'Handwerk', smithing:'Schmieden', trading:'Handel', stealth:'Schleichen', leadership:'Führung' };

export const RARITY = { common:'Gewöhnlich', uncommon:'Ungewöhnlich', rare:'Selten', epic:'Episch', legendary:'Legendär' };

// wtype steuert Angriffsverhalten: reach(px), arc(rad), speed(ms), stam
export const ITEMS = {
  rusty_sword:  { name:'Rostiges Kurzschwert', slot:'weapon', wtype:'sword', dmg:7, reach:40, arc:1.5, speed:520, stam:7, rarity:'common', value:18, skill:'onehanded' },
  longsword:    { name:'Langschwert', slot:'weapon', wtype:'sword', dmg:12, reach:46, arc:1.6, speed:560, stam:9, rarity:'uncommon', value:90, skill:'onehanded' },
  frostblade:   { name:'Frostklinge', slot:'weapon', wtype:'sword', dmg:16, reach:48, arc:1.6, speed:560, stam:9, rarity:'epic', value:320, skill:'onehanded',
                  lore:'Königseisen aus der Tiefhall, in Nordfurt geschmiedet. Im Warmen beschlägt die Klinge.' },
  greatsword:   { name:'Zweihänder', slot:'weapon', wtype:'great', dmg:22, reach:56, arc:2.5, speed:980, stam:18, rarity:'rare', value:220, skill:'twohanded', twohand:true },
  axe:          { name:'Beil', slot:'weapon', wtype:'axe', dmg:11, reach:38, arc:1.2, speed:680, stam:10, ap:0.25, rarity:'common', value:34, skill:'onehanded', tool:'chop' },
  greataxe:     { name:'Große Axt', slot:'weapon', wtype:'great', dmg:25, reach:52, arc:2.2, speed:1080, stam:20, ap:0.35, rarity:'rare', value:260, skill:'twohanded', twohand:true, tool:'chop' },
  mace:         { name:'Streitkolben', slot:'weapon', wtype:'mace', dmg:13, reach:36, arc:1.3, speed:740, stam:11, ap:0.4, stagger:1.6, rarity:'uncommon', value:110, skill:'onehanded' },
  spear:        { name:'Speer', slot:'weapon', wtype:'spear', dmg:10, reach:74, arc:0.5, speed:640, stam:8, rarity:'common', value:48, skill:'polearms' },
  dagger:       { name:'Dolch', slot:'weapon', wtype:'dagger', dmg:5, reach:26, arc:1.1, speed:300, stam:4, crit:2.6, rarity:'common', value:22, skill:'onehanded' },
  shortbow:     { name:'Kurzbogen', slot:'weapon', wtype:'bow', dmg:9, reach:360, speed:820, stam:8, rarity:'common', value:55, skill:'archery', ranged:true },
  longbow:      { name:'Langbogen', slot:'weapon', wtype:'bow', dmg:15, reach:460, speed:1080, stam:11, rarity:'rare', value:190, skill:'archery', ranged:true, twohand:true },
  pickaxe:      { name:'Spitzhacke', slot:'weapon', wtype:'axe', dmg:8, reach:34, arc:1.1, speed:760, stam:9, rarity:'common', value:26, skill:'onehanded', tool:'mine' },
  staff:        { name:'Stab', slot:'weapon', wtype:'staff', dmg:6, reach:40, arc:1.4, speed:620, stam:6, rarity:'common', value:40, skill:'unarmed', mana:12, twohand:true },

  wooden_shield:{ name:'Holzschild', slot:'offhand', block:0.30, armor:2, rarity:'common', value:28 },
  buckler:      { name:'Eisenbuckler', slot:'offhand', block:0.24, armor:1, rarity:'common', value:36 },
  kite_shield:  { name:'Normannenschild', slot:'offhand', block:0.42, armor:4, weight:2, rarity:'uncommon', value:130 },
  tower_shield: { name:'Turmschild', slot:'offhand', block:0.58, armor:6, weight:5, slow:0.22, rarity:'rare', value:280 },

  cloth_shirt:  { name:'Leinenkittel', slot:'chest', armor:1, rarity:'common', value:8 },
  leather_jerkin:{name:'Lederwams', slot:'chest', armor:4, rarity:'common', value:45 },
  chain_hauberk:{ name:'Kettenpanzer', slot:'chest', armor:9, weight:3, rarity:'uncommon', value:190 },
  plate_cuirass:{ name:'Plattenharnisch', slot:'chest', armor:15, weight:6, slow:0.12, rarity:'rare', value:460 },
  leather_cap:  { name:'Lederkappe', slot:'head', armor:2, rarity:'common', value:20 },
  iron_helm:    { name:'Eisenhelm', slot:'head', armor:5, weight:1, rarity:'uncommon', value:95 },
  leather_boots:{ name:'Lederstiefel', slot:'feet', armor:1, rarity:'common', value:16 },
  traveler_cloak:{name:'Reisemantel', slot:'cloak', armor:1, cold:1, rarity:'common', value:24 },

  bread:      { name:'Brotlaib', slot:'consumable', use:'food', heal:6, food:1, stack:9, rarity:'common', value:4 },
  dried_meat: { name:'Dörrfleisch', slot:'consumable', use:'food', heal:10, food:2, stack:9, rarity:'common', value:9 },
  herb:       { name:'Heilkraut', slot:'consumable', use:'bandage', heal:10, stack:9, rarity:'common', value:12, lore:'Als Umschlag auf eine Wunde gelegt.' },
  potion:     { name:'Trank der Genesung', slot:'consumable', use:'heal', heal:40, stack:5, rarity:'uncommon', value:55 },
  bandage:    { name:'Verband', slot:'consumable', use:'bandage', stack:10, rarity:'common', value:9, lore:'Heilt ein Körperteil und stillt Blutungen. Anlegen dauert.' },

  wood:  { name:'Bauholz', slot:'material', res:'wood', stack:99, rarity:'common', value:2 },
  stone: { name:'Bruchstein', slot:'material', res:'stone', stack:99, rarity:'common', value:2 },
  iron:  { name:'Eisenerz', slot:'material', res:'iron', stack:99, rarity:'common', value:6 },
  pelt:  { name:'Wolfsfell', slot:'material', good:true, stack:20, rarity:'common', value:14 },
  bone:  { name:'Alter Knochen', slot:'material', stack:20, rarity:'common', value:3 },
  grain: { name:'Weizensack', slot:'material', good:true, stack:20, rarity:'common', value:6 },
  salt:  { name:'Salzsack', slot:'material', good:true, stack:20, rarity:'common', value:8 },
  cloth: { name:'Tuchballen', slot:'material', good:true, stack:20, rarity:'common', value:12 },

  gorak_cleaver:{ name:'Goraks Hackmesser', slot:'weapon', wtype:'axe', dmg:18, reach:44, arc:1.5, speed:760, stam:13, ap:0.3,
                  rarity:'epic', value:340, skill:'onehanded', lore:'Aus Grubenwerkzeug geschmiedet. Das Blatt ist nie gereinigt worden.' },
  order_seal:   { name:'Siegel des Ordens', slot:'cloak', armor:2, holy:0.2, rarity:'rare', value:200, lore:'Elfenbein und altes Rot. Es wiegt mehr, als es sollte.' },
  grave_seal:   { name:'Grabsiegel', slot:'material', stack:1, rarity:'rare', value:0, lore:'Kalt, auch in der Sonne.' },
  soul_vial:    { name:'Seelenphiole', slot:'consumable', use:'soul', stack:5, rarity:'uncommon', value:40, lore:'Ein Hauch, abgefüllt. Totenrufer trinken daraus, Hexer löschen damit.' },
  kings_iron:   { name:'Königseisen', slot:'material', stack:1, rarity:'rare', value:0, lore:'Ein Barren mit dem Hammerzeichen der alten Bergleute. Kalt, auch in der Hand.' },
  ancestor_urn: { name:'Ahnenurne', slot:'material', stack:1, rarity:'epic', value:0, lore:'Asche von tausend Namen. Wer sie trägt, hört sie flüstern.' },
};

export const LOOT = {
  wolf:      [['pelt',0.7],['dried_meat',0.4],['bone',0.3]],
  boar:      [['dried_meat',0.8],['pelt',0.3]],
  goblin:    [['bone',0.4],['rusty_sword',0.12],['bread',0.3],['iron',0.2],['bandage',0.15]],
  goblin_warrior:[['iron',0.5],['axe',0.2],['leather_cap',0.15],['spear',0.12]],
  bandit:    [['rusty_sword',0.2],['leather_jerkin',0.15],['bread',0.4],['dagger',0.2],['bandage',0.35]],
  bandit_archer:[['shortbow',0.25],['leather_cap',0.2],['dried_meat',0.3]],
  skeleton:  [['bone',0.9],['rusty_sword',0.2],['grave_seal',0.05]],
  gorak:     [['gorak_cleaver',1],['iron',1],['iron',1],['potion',0.6]],
  crypt_warden:[['ancestor_urn',1],['bone',1],['chain_hauberk',0.4]],
  hrodvar:   [['plate_cuirass',0.5],['iron_helm',0.6],['iron',1],['potion',1]],
};

// interiors: folgt dem Spieler durch Eingänge (Grube, Dungeons). Tiere nicht — sie lauern draußen (GDD §Übergänge).
export const MONSTERS = {
  wolf:      { name:'Wolf', hp:30, dmg:7, speed:1.55, reach:26, atk:900, xp:12, sight:220, r:11, threat:1, faction:'beast', interiors:false, pal:{body:'#5b5145',dark:'#3a332b',eye:'#c8a545'} },
  boar:      { name:'Wildschwein', hp:46, dmg:11, speed:1.35, reach:26, atk:1200, xp:16, sight:170, r:13, threat:1, faction:'beast', interiors:false, pal:{body:'#4b3f34',dark:'#2f271f',eye:'#b8503a'} },
  goblin:    { name:'Goblin', hp:28, dmg:6, speed:1.35, reach:28, atk:820, xp:12, sight:210, r:10, threat:1, faction:'goblin', interiors:true, pal:{skin:'#6d7a45',cloth:'#4a3a28',metal:'#6b6156'} },
  goblin_warrior:{ name:'Goblin-Krieger', hp:54, dmg:11, speed:1.25, reach:32, atk:1000, xp:26, sight:230, r:12, threat:2, faction:'goblin', interiors:true, pal:{skin:'#5f6e3c',cloth:'#3d2f20',metal:'#8a7f6d'} },
  bandit:    { name:'Bandit', hp:48, dmg:10, speed:1.4, reach:34, atk:880, xp:22, sight:250, r:11, threat:2, faction:'bandit', interiors:true, pal:{skin:'#b2926f',cloth:'#4a3226',metal:'#7d7364'} },
  bandit_archer:{ name:'Banditenschütze', hp:36, dmg:9, speed:1.35, reach:300, atk:1500, ranged:true, xp:24, sight:320, r:11, threat:2, faction:'bandit', interiors:true, pal:{skin:'#b2926f',cloth:'#3f4a2e',metal:'#7d7364'} },
  skeleton:  { name:'Untoter Krieger', hp:44, dmg:10, speed:1.15, reach:32, atk:1000, telegraph:380, xp:28, sight:240, r:11, threat:2, faction:'undead', interiors:true, pal:{skin:'#cfc8b4',cloth:'#22252a',metal:'#3f4b46',glow:'#4e8f7a'} },
  crypt_warden:{ name:'Wächter der Nekropole', hp:150, dmg:15, speed:1.1, reach:40, atk:1300, telegraph:520, xp:90, sight:260, r:13, threat:3, faction:'undead', interiors:true,
               pal:{skin:'#d8d0ba',cloth:'#1c1f24',metal:'#4a4f55',glow:'#7fd0b8'} },
  hrodvar:   { name:'Hrodvar, König unter dem Eis', hp:280, dmg:19, speed:1.0, reach:46, atk:1500, telegraph:650, xp:220, sight:280, r:14, boss:true, threat:4, faction:'undead', interiors:false,
               pal:{skin:'#d4dde2',cloth:'#1d2a36',metal:'#8fb3c7',glow:'#9fd8ff'} },   // Tiefhall; eigene Angriffsmuster erst mit Phase 12
  valen_soldier:{ name:'Soldat Valens', hp:52, dmg:10, speed:1.3, reach:44, atk:950, xp:0, sight:260, r:11, threat:2, faction:'valen', interiors:true, pal:{skin:'#c9a582',cloth:'#2f4260',metal:'#9aa3b0'} },
  gorak:     { name:'Gorak, Grubenwart', hp:240, dmg:24, speed:1.0, reach:52, atk:2000, telegraph:800, xp:180, sight:300, r:20, boss:true, threat:4, faction:'goblin', interiors:false, pal:{skin:'#556b34',cloth:'#33261a',metal:'#9a8e78'} },
};

// Klassenbaum: parent = Voraussetzung
export const CLASSES = {
  wanderer:  { name:'Wanderer', tier:0 },
  warrior:   { name:'Krieger', tier:1, parent:'wanderer', abilities:['power_strike'], desc:'Stahl und Standhaftigkeit.' },
  archer:    { name:'Schütze', tier:1, parent:'wanderer', abilities:['aimed_shot'], desc:'Abstand ist eine Waffe.' },
  rogue:     { name:'Schurke', tier:1, parent:'wanderer', abilities:['backstab'], desc:'Der erste Schlag zählt doppelt.' },
  cleric:    { name:'Kleriker', tier:1, parent:'wanderer', abilities:['holy_heal'], desc:'Licht als Handwerk.' },
  mage:      { name:'Magier', tier:1, parent:'wanderer', abilities:['fireball'], desc:'Feuer gehorcht, kurz.' },
  knight:    { name:'Ritter', tier:2, parent:'warrior', abilities:['power_strike','blessing'], desc:'Ein Eid mit Rüstung.' },
  paladin:   { name:'Paladin', tier:3, parent:'knight', abilities:['holy_strike','blessing','holy_heal'], faction:'order',
               desc:'Ein Schwert macht dich nicht zum Ritter. Was du beschützt, tut es.' },
  ranger:    { name:'Waldläufer', tier:2, parent:'archer', abilities:['aimed_shot','mark_target'], desc:'Der Wald ist eine Karte, die nur du liest.' },
  deathknight:{name:'Todesritter', tier:3, parent:'warrior', abilities:['life_drain','power_strike'], faction:'undead', desc:'Treue über den Tod hinaus.' },
};

export const ABILITIES = {
  power_strike:{ name:'Wuchtschlag', cd:6000, stam:22, icon:'strike', desc:'Doppelter Waffenschaden, kurze Betäubung.' },
  aimed_shot:  { name:'Gezielter Schuss', cd:7000, stam:18, icon:'arrow', desc:'Weit reichender Schuss, hoher kritischer Anteil.' },
  backstab:    { name:'Meuchelstich', cd:8000, stam:20, icon:'dagger', desc:'Dreifacher Schaden von hinten.' },
  holy_heal:   { name:'Heiliges Heilen', cd:9000, mana:18, icon:'heal', desc:'Heilt dich oder den nächsten Gefährten.' },
  fireball:    { name:'Feuerball', cd:5000, mana:16, icon:'fire', desc:'Fliegendes Feuer, Flächenschaden beim Einschlag.' },
  shadow_bolt: { name:'Schattenblitz', cd:4000, mana:14, icon:'shadow', desc:'Schattenschaden auf Distanz.' },
  life_drain:  { name:'Lebensentzug', cd:11000, mana:20, icon:'drain', desc:'Schaden, der dich heilt.' },
  holy_strike: { name:'Heiliger Schlag', cd:7000, mana:14, icon:'holy', desc:'Schwerer Schaden gegen Untote und Verfluchte.' },
  blessing:    { name:'Segen', cd:20000, mana:16, icon:'bless', desc:'Rüstung der Gruppe steigt für 20 Sekunden.' },
  mark_target: { name:'Ziel markieren', cd:12000, stam:10, icon:'mark', desc:'Markiertes Ziel nimmt 25% mehr Schaden.' },
  // ---- Titelfähigkeiten: kosten die Ressource ihrer Titelklasse (cost) oder laden sie auf (gain), nie Mana/Ausdauer ----
  raise_dead:  { name:'Totenruf', title:'necromancer', cd:4000, cost:2, desc:'Eine Leiche in der Nähe steht als Diener auf (60 s, höchstens 2). Kostet 2 Seelenessenz.' },
  bone_ward:   { name:'Knochenschild', title:'necromancer', cd:12000, cost:1, desc:'Knochen fangen die nächsten 25 Schaden ab (10 s). Kostet 1 Seelenessenz.' },
  soul_harvest:{ name:'Seelenernte', title:'necromancer', cd:20000, cost:'all', desc:'Verbraucht alle Essenz: heilt dich und deine Diener, entzieht Feinden ringsum Leben.' },
  hex:         { name:'Fluch', title:'warlock', cd:6000, gain:20, desc:'Das nächste Ziel nimmt 12 s lang 25 % mehr Schaden und wird langsamer. +20 Verderbnis.' },
  chaos_bolt:  { name:'Chaosblitz', title:'warlock', cd:2500, gain:15, desc:'Schattengeschoss; Schaden steigt mit der Verderbnis (bis ×2). +15 Verderbnis.' },
  roots:       { name:'Rankenfessel', title:'druid', cd:7000, cost:25, desc:'Ranken halten das nächste Ziel 3 s fest. Kostet 25 Wildkraft.' },
  spirit_wolf: { name:'Geisterwolf', title:'druid', cd:15000, cost:40, desc:'Ein Wolf aus Nebel kämpft 30 s an deiner Seite. Kostet 40 Wildkraft.' },
  earth_blessing:{ name:'Erdsegen', title:'druid', cd:14000, cost:30, desc:'Dich und deine Gruppe heilt die Erde 8 s lang. Kostet 30 Wildkraft.' },
  unleash:     { name:'Entfesseln', title:'warlock', cd:15000, min:40, cost:'all', desc:'Ab 40 Verderbnis: alles bricht als Ring aus Schatten aus (Schaden = Verderbnis × 0,6). Danach 0.' },
};

// ---- Titelklassen (Session 4, Nutzerwunsch): später freigeschaltet, getragen wie ein Titel, neben der Grundklasse ----
// Die Grundklasse (Klassenbaum oben) bleibt die Kampfbasis mit Mana/Ausdauer. Eine Titelklasse kommt dazu — nie im Menü,
// immer durch eine Tat in der Welt — und bringt: eine eigene Ressource mit eigener Regel (keine Ruhe-Regeneration),
// drei Sonderfähigkeiten, die nur diese Ressource nutzen, ein Passiv, einen ehrlichen Makel, Kosten beim Pakt,
// Fraktionsfolgen und ein sichtbares Merkmal. Aktiv ist höchstens eine; Pakte schließen einander aus (excludes).
export const TITLE_CLASSES = {
  necromancer: { name:'Nekromant', title:'Totenrufer', glow:'#8fd9b0', faction:'undead', excludes:['warlock'], reversible:false,
    desc:'Ein Pakt mit den Ahnen des Totenreichs. Kontrolle statt Zerstörung: die Toten stehen für dich auf.',
    resource:{ key:'essence', name:'Seelenessenz', max:6, start:0, css:'essence',
      rule:'Jeder Tod in deiner Nähe (bis ~9 Schritt) gibt +1, auch durch deine Diener. Sie verfliegt nicht und kommt nicht durch Rast.' },
    abilities:['raise_dead', 'bone_ward', 'soul_harvest'],
    passive:{ name:'Totenwache', desc:'Deine Diener kämpfen für dich; was sie töten, nährt deine Essenz.' },
    flaw:{ name:'Die Toten zehren', desc:'Eigener Waffenschaden −15 %. Heiliges Heilen wirkt auf dich nur halb.' },
    cost:{ desc:'Ein Teil von dir bleibt bei den Toten: Leben −10 % für immer.', hpMul:0.9 },
    rep:{ undead:20, order:-30, valen:-10 },
    unlock:'„Der Pakt der Stillen Schar“: die Ahnenurne aus der Großen Nekropole zu Ysra nach Alt-Vharn bringen.' },
  warlock: { name:'Hexenmeister', title:'Schattengebundener', glow:'#b07ae0', faction:'undead', excludes:['necromancer'], reversible:false,
    desc:'Ein Pakt mit dem, was im Obelisken flüstert. Flüche, Chaos, Macht auf Pump.',
    resource:{ key:'corruption', name:'Verderbnis', max:100, start:20, css:'corruption',
      rule:'Jede Titelfähigkeit lädt sie auf. Außerhalb des Kampfes sinkt sie (−4/s). Stirbt ein Verfluchter, sinkt sie um 15.' },
    abilities:['hex', 'chaos_bolt', 'unleash'],
    passive:{ name:'Macht aus Fäulnis', desc:'Titelzauber kosten kein Mana; ihr Schaden steigt mit der Verderbnis bis aufs Doppelte.' },
    flaw:{ name:'Sie frisst dich', desc:'Über 70 Verderbnis verlierst du Leben (1,5/s). Bei 100 bricht sie aus: 15 Schaden, zurück auf 60.' },
    cost:{ desc:'Der Schatten nimmt Atem: Ausdauer −10 für immer.', stamina:-10 },
    rep:{ undead:15, order:-30, valen:-10 },
    unlock:'„Der Pakt der Stillen Schar“: die Ahnenurne statt zu Ysra zu Vhal, dem Flüsternden, am Nekromanten-Turm bringen.' },
  druid: { name:'Druide', title:'Hainhüter', glow:'#b7d86a', faction:null, excludes:[], reversible:false,
    desc:'Der Wald hat dich angenommen. Kraft aus Wurzel, Rudel und Erde — solange du draußen bist.',
    resource:{ key:'wild', name:'Wildkraft', max:100, start:40, css:'wild',
      rule:'Wächst von selbst (+5/s), aber nur draußen auf Gras, Erde und Sumpf. In Siedlungen, auf Stein und Asche, unter Tage steht sie still.' },
    abilities:['roots', 'spirit_wolf', 'earth_blessing'],
    passive:{ name:'Waldgänger', desc:'Draußen in der Natur heilen deine Wunden langsam von selbst (0,5 Leben/s).' },
    flaw:{ name:'Metall erstickt', desc:'In Ketten- oder Plattenpanzer wächst die Wildkraft nur halb so schnell.' },
    cost:{ desc:'Der Hain nimmt, was er gibt: Stärke −1 für immer.', attr:{ strength:-1 } },
    rep:{ order:5 },
    unlock:'„Der Ruf des Hains“: Mira im Alten Hain des Westwalds helfen — das Rudel der Wolfsschlucht vertreiben, Heilkraut für die Quelle bringen.' },
};
export const MAX_TITLES = 2;                       // höchstens zwei Titelklassen je Figur (Nutzerwunsch), getragen wird eine

// ---- Skill-Baum (Session 5): 1 Punkt je Stufe. Allgemeine Zweige für alle, dazu ein Zweig je Titelklasse, der erst mit ihr
// erscheint. requires = einer der genannten Knoten reicht (Pfad), [] = Einstieg. Effekte addieren sich (fx), besondere Regeln
// hängen am Knoten-Schlüssel (keystone). Jeder Schlüsselknoten hat einen Preis und ein designIntent — ohne Absicht kein Knoten.
export const SKILL_BRANCHES = {
  combat:  { name:'Kampf', desc:'Wer vorne steht.' },
  magic:   { name:'Magie', desc:'Wer von weitem entscheidet.' },
  survival:{ name:'Überleben', desc:'Wer am Ende noch steht.' },
  necromancer:{ name:'Nekromantie', title:'necromancer', desc:'Nur für Nekromanten.' },
  warlock:{ name:'Hexerei', title:'warlock', desc:'Nur für Hexenmeister.' },
  druid:  { name:'Hainkunde', title:'druid', desc:'Nur für Druiden.' },
};
export const SKILL_TREE = {
  // Kampf
  c_tough:  { branch:'combat', row:0, name:'Zähigkeit', fx:{ hp:0.08 }, requires:[], desc:'Leben +8 %.' },
  c_strike: { branch:'combat', row:0, name:'Kraftschlag', fx:{ dmg:0.06 }, requires:[], desc:'Waffenschaden +6 %.' },
  c_skin:   { branch:'combat', row:1, name:'Eiserne Haut', fx:{ armor:2 }, requires:['c_tough'], desc:'Rüstung +2.' },
  c_edge:   { branch:'combat', row:1, name:'Klingenmeister', fx:{ crit:0.04 }, requires:['c_strike'], desc:'Kritische Treffer +4 %.' },
  c_breath: { branch:'combat', row:1, name:'Kampfatem', fx:{ stam:15 }, requires:['c_tough', 'c_strike'], desc:'Ausdauer +15.' },
  c_wall:   { branch:'combat', row:2, type:'notable', name:'Schildwall', fx:{ armor:4, hp:0.05 }, requires:['c_skin'], desc:'Rüstung +4, Leben +5 %.' },
  c_butcher:{ branch:'combat', row:2, type:'notable', name:'Schlächter', fx:{ dmg:0.10, crit:0.03 }, requires:['c_edge'], desc:'Waffenschaden +10 %, Krit +3 %.' },
  k_berserk:{ branch:'combat', row:3, type:'keystone', name:'Berserker', fx:{}, requires:['c_butcher'],
    desc:'Unter 30 % Leben: Schaden +25 %. Dafür nimmst du immer 15 % mehr Schaden.', designIntent:'Risiko als Waffe: wer nah am Tod kämpft, wird gefährlicher — Gegenpol zum Bollwerk.' },
  k_bulwark:{ branch:'combat', row:3, type:'keystone', name:'Bollwerk', fx:{}, requires:['c_wall'],
    desc:'Rüstung +30 %. Dafür 10 % langsamer.', designIntent:'Stehen statt tanzen: Treffer einstecken, dafür schlechter fliehen und ausweichen.' },
  // Magie
  m_vein:   { branch:'magic', row:0, name:'Arkane Ader', fx:{ mana:15 }, requires:[], desc:'Mana +15 (wer Mana hat).' },
  m_quick:  { branch:'magic', row:0, name:'Gedankenschnelle', fx:{ cdr:0.05 }, requires:[], desc:'Abklingzeiten −5 %.' },
  m_power:  { branch:'magic', row:1, name:'Zauberkraft', fx:{ spell:0.08 }, requires:['m_vein'], desc:'Zauberschaden +8 %.' },
  m_focus:  { branch:'magic', row:1, name:'Sammlung', fx:{ manaRegen:0.5 }, requires:['m_vein'], desc:'Mana kehrt 50 % schneller zurück.' },
  m_flow:   { branch:'magic', row:2, type:'notable', name:'Fluss', fx:{ cdr:0.08 }, requires:['m_quick', 'm_focus'], desc:'Abklingzeiten −8 %.' },
  m_soul:   { branch:'magic', row:2, type:'notable', name:'Feuerseele', fx:{ spell:0.12 }, requires:['m_power'], desc:'Zauberschaden +12 %.' },
  k_glass:  { branch:'magic', row:3, type:'keystone', name:'Glaskanone', fx:{ spell:0.30, hp:-0.15 }, requires:['m_soul'],
    desc:'Zauberschaden +30 %. Leben −15 %.', designIntent:'Zauber entscheiden den Kampf, bevor er dich erreicht — oder du stirbst schneller.' },
  k_scholar:{ branch:'magic', row:3, type:'keystone', name:'Gelehrter Geist', fx:{ cdr:0.15, dmg:-0.15 }, requires:['m_flow'],
    desc:'Abklingzeiten −15 %. Waffenschaden −15 %.', designIntent:'Fähigkeiten statt Klinge: öfter zaubern, schwächer zuschlagen.' },
  // Überleben
  s_life:   { branch:'survival', row:0, name:'Lebenskraft', fx:{ hp:0.06 }, requires:[], desc:'Leben +6 %.' },
  s_light:  { branch:'survival', row:0, name:'Leichtfüßig', fx:{ speed:0.04 }, requires:[], desc:'Tempo +4 %.' },
  s_medic:  { branch:'survival', row:1, name:'Feldscher', fx:{ heal:0.20 }, requires:['s_life'], desc:'Heilung durch Kräuter, Verbände, Tränke +20 %.' },
  s_endure: { branch:'survival', row:1, name:'Ausdauernd', fx:{ regen:0.25 }, requires:['s_light'], desc:'Ausdauer kehrt 25 % schneller zurück.' },
  s_pack:   { branch:'survival', row:1, name:'Packesel', fx:{ invCap:6 }, requires:['s_light'], desc:'6 Plätze mehr im Gepäck.' },
  s_dodge:  { branch:'survival', row:2, type:'notable', name:'Ausweichkünstler', fx:{ dodge:0.30, speed:0.03 }, requires:['s_endure'], desc:'Ausweichen kostet 30 % weniger Ausdauer, Tempo +3 %.' },
  s_wound:  { branch:'survival', row:2, type:'notable', name:'Wundheiler', fx:{ heal:0.25, hp:0.05 }, requires:['s_medic'], desc:'Heilung +25 %, Leben +5 %.' },
  k_second: { branch:'survival', row:3, type:'keystone', name:'Zweiter Atem', fx:{ hp:-0.05 }, requires:['s_wound'],
    desc:'Fällst du unter 25 % Leben, kommen 30 % zurück und die Ausdauer füllt sich — höchstens alle 3 Minuten. Leben −5 %.', designIntent:'Ein Fehler wird verziehen, zwei nicht: rettet den Kampf, nicht den Leichtsinn.' },
  k_wild:   { branch:'survival', row:3, type:'keystone', name:'Wildnisläufer', fx:{}, requires:['s_dodge'],
    desc:'Außerhalb von Siedlungen: Tempo +10 %, Ausdauer kehrt 50 % schneller zurück. In Siedlungen Tempo −5 %.', designIntent:'Für Reisende und Jäger: die Welt ist groß — wer draußen lebt, wird dort stärker.' },
  // Nekromantie (erst mit der Titelklasse)
  n_bind:   { branch:'necromancer', row:0, name:'Knochenbinder', fx:{}, requires:[], desc:'Diener bleiben 20 s länger.' },
  n_vessel: { branch:'necromancer', row:0, name:'Seelengefäß', fx:{}, requires:[], desc:'Seelenessenz fasst 2 mehr.' },
  n_cold:   { branch:'necromancer', row:1, name:'Grabkälte', fx:{}, requires:['n_bind'], desc:'Diener haben 25 % mehr Leben.' },
  n_reap:   { branch:'necromancer', row:1, type:'notable', name:'Ernte der Toten', fx:{}, requires:['n_vessel'], desc:'Seelenernte wirkt 50 % stärker.' },
  k_legion: { branch:'necromancer', row:2, type:'keystone', name:'Legion', fx:{}, requires:['n_cold'],
    desc:'Bis zu 3 Diener gleichzeitig. Dein eigener Waffenschaden −20 %.', designIntent:'Kontrolle statt Einzelkampf: der Nekromant wird zum Feldherrn, nicht zum Fechter.' },
  // Hexerei
  w_deep:   { branch:'warlock', row:0, name:'Tiefer Schatten', fx:{}, requires:[], desc:'Verderbnis frisst erst ab 85 statt 70.' },
  w_eye:    { branch:'warlock', row:0, name:'Böser Blick', fx:{}, requires:[], desc:'Fluch hält 6 s länger.' },
  w_core:   { branch:'warlock', row:1, name:'Chaoskern', fx:{}, requires:['w_eye'], desc:'Chaosblitz +20 % Schaden.' },
  w_rift:   { branch:'warlock', row:1, type:'notable', name:'Weiter Riss', fx:{}, requires:['w_deep'], desc:'Entfesseln trifft 40 px weiter.' },
  k_bloodpact:{ branch:'warlock', row:2, type:'keystone', name:'Blutpakt', fx:{}, requires:['w_core'],
    desc:'Titelzauber +25 % Schaden. Die Verderbnis sinkt außerhalb des Kampfes nicht mehr.', designIntent:'Kein Durchatmen: mehr Macht, aber der Schatten bleibt — jeder Kampf beginnt schon angefressen.' },
  // Hainkunde
  d_roots:  { branch:'druid', row:0, name:'Tiefe Wurzeln', fx:{}, requires:[], desc:'Rankenfessel hält 1 s länger.' },
  d_spring: { branch:'druid', row:0, name:'Quellgrund', fx:{}, requires:[], desc:'Wildkraft wächst 30 % schneller.' },
  d_pack:   { branch:'druid', row:1, name:'Rudelband', fx:{}, requires:['d_spring'], desc:'Der Geisterwolf bleibt 15 s länger.' },
  d_earth:  { branch:'druid', row:1, type:'notable', name:'Heilende Erde', fx:{}, requires:['d_roots'], desc:'Erdsegen heilt 50 % mehr.' },
  k_grove:  { branch:'druid', row:2, type:'keystone', name:'Hüter des Hains', fx:{}, requires:['d_pack', 'd_earth'],
    desc:'Auf Gras und im Wald: Schaden +15 %, Rüstung +3. Auf Stein, Asche und in Siedlungen: Schaden −10 %.', designIntent:'Der Druide gehört nach draußen: stark im Wald, schwach in Stein und Stadt.' },
};

export const FACTIONS = {
  valen: { name:'Königreich Valen', colors:['#2f4260','#b9c3d2'], desc:'Ordnung, Steuern, Garnisonen. Was davon übrig ist.',
           ranks:['Rekrut','Soldat','Veteran','Ritter','Offizier'] },
  order: { name:'Der Orden', colors:['#d9d2c0','#9b2e26'], desc:'Elfenbein und Eisen gegen das, was nicht sterben will.',
           ranks:['Novize','Akolyth','Wächter','Ritter','Paladin','Meister'] },
  undead:{ name:'Die Untoten', colors:['#1d2422','#4e8f7a'], desc:'Eine Zivilisation, keine Monsterschar. Sie haben Städte und Geduld.',
           ranks:['Diener','Adept','Grabgebundener','Todesritter','Kommandant'] },
  merch: { name:'Freie Händler', colors:['#3c3324','#bd9433'], desc:'Wo Krieg ist, ist Nachfrage.' , ranks:['Kunde','Partner','Teilhaber']},
  bandit:{ name:'Rooks Bande', colors:['#2a231a','#8c3b2a'], desc:'Kein Banner, keine Steuern, kurze Leben.', ranks:['Handlanger','Klinge','Hauptmann'] },
};

export const NPCS = [
  { key:'havel', name:'Havel', prof:'Dorfvorsteher', faction:'valen', age:54, home:'village', x:0, y:0,
    traits:['diszipliniert','vorsichtig'], attrs:{intelligence:11,willpower:10}, cls:'wanderer', recruit:false,
    greet:'„Fremde bringen entweder Arbeit oder Ärger. Welches von beidem bist du?“' },
  { key:'elena', name:'Elena', prof:'Heilerin', faction:'order', age:27, home:'village',
    traits:['gütig','loyal','vorsichtig'], attrs:{intelligence:12,agility:8}, cls:'cleric', recruit:true, recruitRel:25,
    greet:'„Du siehst nicht aus wie jemand, der viel Gold besitzt.“', teaches:'cleric' },
  { key:'tomas', name:'Tomas', prof:'Jägerbursche', faction:null, age:18, home:'village',
    traits:['ehrgeizig','neugierig'], attrs:{agility:12,perception:11}, cls:'archer', recruit:true, recruitRel:15,
    greet:'„Ich treffe alles unter dreißig Schritt. Fast alles.“', teaches:'archer', kin:'son' },
  { key:'borin', name:'Borin', prof:'Ehemaliger Söldner', faction:null, age:42, home:'tavern',
    traits:['diszipliniert','misstrauisch'], attrs:{strength:14,endurance:13}, cls:'warrior', recruit:true, recruitRel:35,
    greet:'„Ich arbeite für Leute, die wissen, wohin sie gehen. Weißt du es?“', teaches:'warrior' },
  { key:'mara', name:'Mara', prof:'Händlerin', faction:'merch', age:36, home:'market',
    traits:['klug','praktisch'], attrs:{intelligence:12,perception:10}, cls:'wanderer', recruit:false,
    greet:'„Kaufen, verkaufen, oder im Weg stehen. Such dir eins aus.“', shop:true, town:'eren' },
  { key:'gerold', name:'Gerold', prof:'Kontorhändler', faction:'merch', age:51, home:'northcity',
    traits:['gierig','praktisch'], attrs:{intelligence:12}, cls:'wanderer', recruit:false,
    greet:'„Nordfurt zahlt für Weizen. Eren zahlt für Salz. Der Rest ist Straße.“', shop:true, town:'northcity' },
  { key:'aldric', name:'Aldric', prof:'Schmied', faction:null, age:48, home:'smithy',
    traits:['diszipliniert','mürrisch'], attrs:{strength:12,crafting:14}, cls:'warrior', recruit:false,
    greet:'„Bring mir Eisen, dann reden wir über Stahl.“', smith:true },
  { key:'jorun', name:'Jorun', prof:'Bauer', faction:null, age:45, home:'farm',
    traits:['furchtsam','gütig'], attrs:{endurance:11}, cls:'wanderer', recruit:false,
    greet:'„Bitte. Meine Tochter ist seit zwei Tagen fort.“' },
  { key:'kelan', name:'Kelan der Graue', prof:'Alter Paladin', faction:'order', age:61, home:'shrine',
    traits:['diszipliniert','gütig'], attrs:{strength:13,willpower:15}, cls:'paladin', recruit:false,
    greet:'„Ein Schwert macht dich nicht zum Ritter. Was du beschützt, tut es.“', teaches:'paladin' },
  { key:'rook', name:'Rook', prof:'Bandenführer', faction:'bandit', age:38, home:'banditcamp',
    traits:['grausam','ehrgeizig'], attrs:{strength:13,agility:12}, cls:'rogue', recruit:true, recruitRel:60, hostile:true,
    greet:'„Du bist weit von der Straße abgekommen.“', teaches:'rogue' },
  { key:'morvath', name:'Morvath', prof:'Grabgebundener', faction:'undead', age:0, home:'graveyard',
    traits:['geduldig','kalt'], attrs:{intelligence:14,willpower:14}, cls:'mage', recruit:false, undead:true,
    greet:'„Die Lebenden sind laut. Du bist leiser als die meisten.“' },
  { key:'ysra', name:'Ysra', prof:'Stimme der Gruft', faction:'undead', age:0, home:'altvharn',
    traits:['geduldig','streng'], attrs:{intelligence:15,willpower:16}, cls:'mage', recruit:false, undead:true,
    greet:'„Alt-Vharn war eine Stadt. Die Ahnen wohnen noch hier. Sprich leise.“' },
  { key:'vhal', name:'Vhal', prof:'Der Flüsternde', faction:'undead', age:0, home:'necrotower',
    traits:['gierig','kalt'], attrs:{intelligence:16,willpower:12}, cls:'mage', recruit:false, undead:true,
    greet:'„Ysra will die Toten ordnen. Ich will, dass sie tanzen. Was willst du?“' },
  { key:'mira', name:'Mira', prof:'Hüterin des Hains', faction:null, age:66, home:'grove',
    traits:['geduldig','gütig'], attrs:{willpower:14,perception:13}, cls:'wanderer', recruit:false,
    greet:'„Tritt leise. Hier wachsen Dinge, die älter sind als dein Königreich.“' },
  { key:'brann', name:'Brann', prof:'Meisterschmiedin', faction:'valen', age:44, home:'northsmith',
    traits:['stolz','genau'], attrs:{strength:13,crafting:16}, cls:'warrior', recruit:false, smith:true,
    greet:'„Nordfurter Stahl hält. Aber es gab einmal Besseres — tief unter dem Frostkamm.“' },
  { key:'sael', name:'Sael', prof:'Totenschreiber', faction:'undead', age:0, home:'vharnholm', undead:true,
    traits:['geduldig','genau'], attrs:{intelligence:14}, cls:'wanderer', recruit:false, shop:true, town:'vharnholm',
    pool:['soul_vial','soul_vial','bone','bandage','herb','dried_meat','chain_hauberk','staff','dagger','traveler_cloak'],
    greet:'„Vharnholm schreibt jeden Namen auf, der durch das Tor kommt. Deinen auch.“' },
  { key:'lila', name:'Lila', prof:'Jorans Tochter', faction:null, age:17, home:'banditcamp',
    traits:['neugierig','ehrgeizig'], attrs:{agility:11}, cls:'wanderer', recruit:true, recruitRel:20, kin:'daughter',
    greet:'„Bitte sag ihm nicht, wo ich bin.“' },
];

export const BUILDINGS = {
  campfire:  { name:'Lagerfeuer', cat:'Grundlage', cost:{wood:5}, time:6, w:1, h:1, desc:'Rasten, kochen, heilen. Der Anfang jeder Siedlung.', pop:0 },
  tent:      { name:'Zelt', cat:'Unterkunft', cost:{wood:8}, time:10, w:2, h:2, desc:'Schlafplatz für zwei. Hält kaum Regen ab.', pop:2 },
  hut:       { name:'Hütte', cat:'Unterkunft', cost:{wood:20,stone:8}, time:22, w:3, h:3, desc:'Festes Dach. Zieht Siedler an.', pop:4 },
  storage:   { name:'Lager', cat:'Produktion', cost:{wood:14}, time:14, w:2, h:2, desc:'Gemeinsamer Vorrat der Siedlung.', pop:0 },
  workbench: { name:'Werkbank', cat:'Produktion', cost:{wood:12,stone:4}, time:12, w:2, h:1, desc:'Einfaches Handwerk und Reparatur.', pop:0 },
  smithy:    { name:'Schmiede', cat:'Produktion', cost:{wood:20,stone:15,iron:10}, time:30, w:3, h:2, desc:'Waffen aus Eisen, Reparatur ohne Meister.', pop:0 },
  farm:      { name:'Ackerfläche', cat:'Versorgung', cost:{wood:10}, time:16, w:3, h:3, desc:'Erzeugt täglich Nahrung.', pop:0 },
  well:      { name:'Brunnen', cat:'Versorgung', cost:{stone:18}, time:18, w:1, h:1, desc:'Moral der Siedlung steigt.', pop:0 },
  palisade:  { name:'Palisade', cat:'Verteidigung', cost:{wood:6}, time:5, w:1, h:1, desc:'Ein Abschnitt Wehrzaun. Blockiert Bewegung.', pop:0 },
  gate:      { name:'Tor', cat:'Verteidigung', cost:{wood:12,iron:4}, time:12, w:2, h:1, desc:'Durchlass in der Palisade.', pop:0 },
  watchtower:{ name:'Wachturm', cat:'Verteidigung', cost:{wood:24,stone:12}, time:26, w:2, h:2, desc:'Warnt früher vor Angriffen.', pop:0 },
};

export const QUESTS = {
  q_wolves: { name:'Wölfe an der Hürde', giver:'havel', desc:'Havel zahlt für drei tote Wölfe am Waldrand.',
    objectives:[{type:'kill',target:'wolf',count:3,text:'Wölfe töten'}],
    reward:{gold:60,rep:{valen:5},xp:40}, turnin:'havel' },
  q_herbs: { name:'Elenas Kräuter', giver:'elena', desc:'Elena braucht drei Heilkräuter für einen Fiebernden.',
    objectives:[{type:'item',target:'herb',count:3,text:'Heilkraut sammeln'}],
    reward:{gold:15,rep:{order:6},xp:30,rel:{elena:20}}, turnin:'elena' },
  q_lila: { name:'Die vermisste Tochter', giver:'jorun', desc:'Joruns Tochter Lila ist seit zwei Tagen fort.',
    objectives:[{type:'find',target:'lila',text:'Lila finden'}],
    reward:{xp:60}, turnin:'jorun', branching:true },
  q_mine: { name:'Was in der Grube haust', giver:'mara', desc:'Die alte Grube ist verloren, seit etwas Großes darin wohnt.',
    objectives:[{type:'kill',target:'gorak',count:1,text:'Gorak töten'}],
    reward:{gold:140,rep:{merch:10,valen:4},xp:150}, turnin:'mara' },
  q_paladin1:{ name:'Prüfung: Wachsamkeit', giver:'kelan', desc:'Kelan verlangt Beweise, nicht Absichten. Tote Untote zählen als Beweis.',
    objectives:[{type:'kill',target:'skeleton',count:4,text:'Untote vernichten'}],
    reward:{xp:80,rep:{order:10}}, turnin:'kelan' },
  q_paladin2:{ name:'Prüfung: Das Siegel', giver:'kelan', desc:'Ein Ordenssiegel blieb in der Grube zurück. Hol es.',
    objectives:[{type:'item',target:'order_seal',count:1,text:'Siegel des Ordens bergen'}],
    reward:{xp:110,rep:{order:12}}, turnin:'kelan' },
  q_paladin3:{ name:'Prüfung: Der Schrein', giver:'kelan', desc:'Halte den Schrein, bis die Toten aufhören zu kommen.',
    objectives:[{type:'hold',target:'shrine',count:1,text:'Den Schrein halten'}],
    reward:{xp:200,rep:{order:20},unlock:'paladin'}, turnin:'kelan' },
  q_undead: { name:'Das Grabsiegel', giver:'morvath', desc:'Morvath will ein Siegel aus dem Moor. Was danach kommt, sagt er nicht.',
    objectives:[{type:'item',target:'grave_seal',count:1,text:'Grabsiegel bergen'}],
    reward:{xp:120,rep:{undead:25,order:-10}}, turnin:'morvath' },
  q_graverobbers: { name:'Grabräuber in der Asche', giver:'sael', desc:'Lebende graben in der Nekropole und am Knochenwald nach Grabgut. Sie nehmen die Namen mit. Bring fünf von ihnen zum Schweigen — dann schreibt Vharnholm deinen Namen in die gute Spalte.',
    objectives:[{type:'kill',target:'bandit',count:5,text:'Grabräuber töten'}],
    reward:{gold:90,xp:140,rep:{undead:15,valen:-5}}, turnin:'sael' },
  q_kingsiron: { name:'Königseisen', giver:'brann', desc:'Unter dem Frostkamm liegt die Tiefhall. Die alten Bergleute schmolzen dort Eisen nur für ihren König — und der König soll sie nie verlassen haben. Bring mir einen Barren aus seinem Hort, und ich schmiede dir eine Klinge, wie Nordfurt keine zweite hat.',
    objectives:[{type:'kill',target:'hrodvar',count:1,text:'Den König unter dem Eis zur Ruhe legen'}, {type:'item',target:'kings_iron',count:1,text:'Königseisen aus dem Hort der Tiefhall'}],
    reward:{gold:80,xp:260,rep:{valen:6},item:'frostblade',take:'kings_iron'}, turnin:'brann' },
  q_grove: { name:'Der Ruf des Hains', giver:'mira', desc:'Das Rudel der Wolfsschlucht treibt sich im Hain herum, seit die Quelle krank ist. Vertreib vier Wölfe und bring mir drei Heilkraut für die Quelle. Dann sehen wir, ob der Wald dich will.',
    objectives:[{type:'kill',target:'wolf',count:4,text:'Wölfe vertreiben'}, {type:'item',target:'herb',count:3,text:'Heilkraut für die Quelle'}],
    reward:{xp:150}, turnin:'mira', pact:true },
  q_pact: { name:'Der Pakt der Stillen Schar', giver:'ysra', desc:'In der Großen Nekropole ruht die Ahnenurne, bewacht von dem, der sie nie losließ. Wer zur Schar gehört, dem öffnet er. Alle anderen müssen an ihm vorbei. Bring die Urne — zu mir, wenn du die Toten führen willst.',
    objectives:[{type:'item',target:'ancestor_urn',count:1,text:'Ahnenurne aus der Großen Nekropole holen'}],
    reward:{xp:200}, turnin:'ysra', pact:true },
  q_rook: { name:'Rooks Angebot', giver:'rook', desc:'Rook will die Straße nach Norden unsicher machen. Er braucht Klingen.',
    objectives:[{type:'kill',target:'bandit_rival',count:2,text:'Rooks Rivalen töten'}],
    reward:{gold:120,rep:{bandit:25,valen:-20},xp:90}, turnin:'rook' },
};

export const MEMORY_TEXT = {
  saved_life:'hat mir das Leben gerettet', gave_weapon:'hat mir meine erste Waffe gegeben',
  recruited:'hat mich aufgenommen', fought_together:'hat neben mir gekämpft',
  friend_died:'war dabei, als ein Freund starb', starved:'hat mich hungern lassen',
  paid:'hat gezahlt, was versprochen war', led_to_victory:'hat uns zum Sieg geführt',
  left_to_die:'hat mich liegen lassen', killed_kin:'hat einen der Meinen getötet',
};

// ---- Phase 18–20: Städte, Märkte, Krieg ----
// prod/use pro Tag. Preis steigt, wenn der Vorrat unter den Bedarf fällt.
export const GOODS = ['grain', 'salt', 'cloth', 'pelt'];
export const TOWNS = {
  eren:      { name:'Eren', pop:40, stock:{ grain:40, salt:6, cloth:5, pelt:8 }, prod:{ grain:7, pelt:2 }, use:{ grain:3, salt:2, cloth:1 } },
  northcity: { name:'Nordfurt', pop:90, stock:{ grain:12, salt:30, cloth:25, pelt:3 }, prod:{ salt:5, cloth:4 }, use:{ grain:8, pelt:2, salt:1 } },
};
// Kriegsknoten = Orte aus world.LOCATIONS. garrison = Verteidiger ohne Heer.
export const WAR_NODES = {
  graveyard: { owner:'undead', garrison:10 }, marsh: { owner:null, garrison:0 }, fortress: { owner:null, garrison:0 },
  ruins: { owner:null, garrison:0 }, eren: { owner:'valen', garrison:14 }, road: { owner:'valen', garrison:4 },
  northcity: { owner:'valen', garrison:40 },
  // Südost-Front: das Totenreich gegen Ostmark und Mittelland
  blackkeep: { owner:'undead', garrison:40 }, necropolis: { owner:'undead', garrison:22 },
  altvharn: { owner:'undead', garrison:16 }, sonnwacht: { owner:'order', garrison:20 },
  kreuzweg: { owner:null, garrison:0 }, ashford: { owner:'valen', garrison:8 },
  saltport: { owner:'valen', garrison:14 }, oldbridge: { owner:null, garrison:0 },
};
export const WAR_EDGES = [['graveyard','marsh'], ['graveyard','fortress'], ['marsh','eren'], ['fortress','eren'],
  ['fortress','ruins'], ['ruins','eren'], ['eren','road'], ['road','northcity'],
  // Süd-/Ostfront
  ['blackkeep','necropolis'], ['necropolis','altvharn'], ['altvharn','sonnwacht'], ['altvharn','oldbridge'],
  ['sonnwacht','ashford'], ['ashford','northcity'], ['kreuzweg','oldbridge'], ['kreuzweg','ashford'],
  ['kreuzweg','eren'], ['oldbridge','saltport'], ['oldbridge','eren']];
